{{ do_shortcode('[mc4wp_form id=27307]') }}   

{{-- 

The following code is generated by Mailchimp for WordPress plugin.

<h4>Sign up for listing alerts</h4>
<label>First Name</label>
<input type="text" name="FNAME" placeholder="First Name">
<label>Last Name</label>
<input type="text" name="LNAME" placeholder="Last Name">
<label for="email">Email address: </label>
<input type="email" id="email" name="EMAIL" placeholder="Your email address" required>

<input class="button" type="submit" value="Sign up"> --}}
